name: daily-report

on:
  # รันอัตโนมัติทุกวันทำการ หลังตลาดไทยปิดและข้อมูลอัปเดตเสร็จ (07:30 น. เวลาไทย = 00:30 UTC)
  schedule:
    - cron: "30 0 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KERNEL_NAME: gha-py311
      TZ: Asia/Bangkok

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Register Jupyter kernel in this venv
        run: |
          python -m ipykernel install --name "${KERNEL_NAME}" --sys-prefix
          jupyter kernelspec list

      # สร้างไฟล์ HTML จากโน้ตบุ๊ก
      - name: Execute notebook -> HTML (hide code)
        run: |
          mkdir -p docs
          jupyter nbconvert \
            --to html \
            --execute \
            --ExecutePreprocessor.kernel_name="${KERNEL_NAME}" \
            --ExecutePreprocessor.timeout=1800 \
            --TemplateExporter.exclude_input=True \
            WFO_test_no_out.ipynb \
            --output "index.html" \
            --output-dir docs

      # 👉 แทรกบรรทัดวันที่รันไว้บนสุดของ index.html
      - name: Insert run date at top of HTML
        run: |
          RUNDATE=$(date '+%Y-%m-%d %H:%M %Z')
          echo "<div style='margin:10px 0;padding:8px 12px;background:#e0f7fa;
                 font-size:16px;'><b>รันอัตโนมัติเมื่อ:</b> ${RUNDATE}</div>" \
                 | cat - docs/index.html > docs/index.tmp && mv docs/index.tmp docs/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4



