name: daily-report

on:
  schedule:
    - cron: "0 21 * * *"   # 04:00 น. เวลาไทย
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KERNEL_NAME: gha-py311

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Register Jupyter kernel in this venv
        run: |
          python -m ipykernel install --name "${KERNEL_NAME}" --sys-prefix
          jupyter kernelspec list

      # รันโน้ตบุ๊ก + ซ่อน code ใน HTML
      - name: Execute notebook -> HTML (hide code)
        run: |
          mkdir -p docs
          jupyter nbconvert \
            --to html \
            --execute \
            --ExecutePreprocessor.kernel_name="${KERNEL_NAME}" \
            --ExecutePreprocessor.timeout=1800 \
            --TemplateExporter.exclude_input=True \
            WFO_test_no_out.ipynb \
            --output "index.html" \
            --output-dir docs

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # ส่งอีเมลแจ้งลิงก์เว็บหลัง deploy สำเร็จ
      - name: Send report email
        if: ${{ success() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: true
          username: ${{ secrets.SMTP_USERNAME }}   # ใส่ใน Secrets
          password: ${{ secrets.SMTP_PASSWORD }}   # Gmail App Password
          subject: "SET25 daily scan is updated"
          to: ${{ secrets.MAIL_TO }}               # maleewong@gmail.com
          from: SET25 Bot <${{ secrets.SMTP_USERNAME }}>
          content_type: text/html
          body: >
            <p>สวัสดีครับ,</p>
            <p>รายงานอัปเดตแล้ว:</p>
            <p><a href="${{ steps.deployment.outputs.page_url }}" target="_blank">
            ${{
              steps.deployment.outputs.page_url
            }}</a></p>
            <p>ช่วง 7 วันล่าสุดแสดงบนหน้ารายงานแล้วครับ</p>
