name: daily-report

on:
  schedule:
    # 04:00 น. เวลาไทย (21:00 UTC)
    - cron: "0 21 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KERNEL_NAME: gha-py311  # ชื่อ kernel ที่จะใช้รันโน้ตบุ๊ก

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Register Jupyter kernel in this venv
        run: |
          python -m ipykernel install --name "${KERNEL_NAME}" --sys-prefix
          echo "===== kernelspec list ====="
          jupyter kernelspec list

      # รันโน้ตบุ๊ก + แปลงเป็น HTML (บังคับ kernel ให้ตรงกับที่เพิ่งลงทะเบียน)
      - name: Execute notebook -> HTML
        run: |
          mkdir -p docs
          jupyter nbconvert \
            --to html \
            --execute \
            --ExecutePreprocessor.kernel_name="${KERNEL_NAME}" \
            --ExecutePreprocessor.timeout=1800 \
            WFO_test_no_out.ipynb \
            --output "index.html" \
            --output-dir docs

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

