name: daily-report

on:
  schedule:
    - cron: "0 21 * * *"   # 04:00 น. ไทย
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KERNEL_NAME: gha-py311
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Register Jupyter kernel in this venv
        run: |
          python -m ipykernel install --name "${KERNEL_NAME}" --sys-prefix
          jupyter kernelspec list

      - name: Execute notebook -> HTML
        run: |
          mkdir -p docs
          jupyter nbconvert \
            --to html \
            --execute \
            --ExecutePreprocessor.kernel_name="${KERNEL_NAME}" \
            --ExecutePreprocessor.timeout=1800 \
            WFO_test_no_out.ipynb \
            --output "index.html" \
            --output-dir docs

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
