name: daily-report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"   # รันทุกวัน 08:00 น. เวลาไทย (1:00 UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily scan (no output folders)
        run: |
          python run_daily.py

      - name: Prepare email body
        id: prep_mail
        run: |
          START_DATE=$(date -d "7 days ago" +'%Y-%m-%d')
          END_DATE=$(date +'%Y-%m-%d')
          echo "START_DATE=$START_DATE" >> $GITHUB_ENV
          echo "END_DATE=$END_DATE" >> $GITHUB_ENV
          echo "BODY=สรุปผลสแกนหุ้น SET25 ระหว่างวันที่ $START_DATE ถึง $END_DATE 
          ดูผลได้ที่: https://maleewong.github.io/set25-daily-scan/" >> $GITHUB_ENV

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "SET25 สรุปรายงานประจำวันที่ ${{ env.END_DATE }}"
          to: maleewong@gmail.com
          from: "GitHub Action <${{ secrets.MAIL_USERNAME }}>"
          body: ${{ env.BODY }}


