name: daily-report

on:
  schedule:
    # รันทุกวันเวลา 04:00 น. ตามเวลาไทย (21:00 UTC)
    - cron: "0 21 * * *"
  workflow_dispatch:  # เผื่อกดรันเองได้

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies + register Jupyter kernel
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # ลงทะเบียน kernel ชื่อ python3 ให้ nbconvert/papermill ใช้งานได้
          python -m ipykernel install --user --name=python3

      # สคริปต์นี้ควร execute notebook (ด้วย papermill) แล้วแปลงเป็น HTML
      # และวางผลลัพธ์ไว้ในโฟลเดอร์ docs/ (เช่น docs/index.html)
      - name: Run notebook and build HTML
        run: python run_daily.py

      # อัปโหลดไฟล์ใน docs/ เพื่อเตรียม deploy เป็น GitHub Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
